site_name: IHC - notes
theme:
  name: material
  features:
    - tabs
    - navigation.section
  palette:
    primary: black

nav:
  - Home: index.md
  - Análise de Requisitos: listas/analise_de_requisitos.md
  - Princípios e Diretrizes: listas/principios.md
