site_name: IHC - notes
copyright: 2022 Nicolas Souza
repo_name: IHC-notes
repo_url: https://github.com/nszchagas/IHC-notes

theme:
  name: material
  features:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Análise de Requisitos: listas/analise_de_requisitos.md
  - Princípios e Diretrizes: listas/principios.md
  - Prototipação: listas/prototipacao.md
  - Verificação e Validação: listas/verificacao_validacao.md
